#pragma once

#define PACKET_PRINT_BUFFER_SIZE 2048
#define PACKET_PRINT_IP_ADDR 0x0A00020F
#define PACKET_PRINT_UDP_PORT 5000
#define PACKET_PRINT_MAX_PAYLOAD_DISPLAY 64

void app_packet_print(void);
